import PixelArt from '../PixelArt';

/**
 * The LSUS wordmark, traced from the university's artwork. 178x60.
 *
 * The building itself is no longer drawn here - the LSU Shreveport scene
 * carries a photographic backdrop of the University Center, so a second
 * building in the sprite would only duplicate it. This leaves the mark
 * floating over the real thing.
 *
 * The purple field is dropped and its ink reassigned: "LSU" keeps the gold,
 * the trailing S and "SHREVEPORT" take the purple, which reads against sky
 * where white would not.
 */
const COLUMNS = 178;
const ROWS = 60;

const PALETTE = {
    'Y': '#fdcc19',
    'P': '#451b7b'
};

const LSUS = `
..YYYYYYYYYYYYYY.................................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY...........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.................................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY...........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.................................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY...........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.................................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY...........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.............................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.............................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.............................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.............................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY.......PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYY...............................YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYY...............................YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYY...............................YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYY..................................YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYY...................................YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYY...................................YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYY...................................YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYY..................................YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.........................YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.......................................................YYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY................................PPPPPPPPPPPPPP
..YYYYYYYYYYYYYY.......................................................YYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY.................................PPPPPPPPPPPPP
..YYYYYYYYYYYYYY.......................................................YYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY.................................PPPPPPPPPPPPP
..YYYYYYYYYYYYYY.......................................................YYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY.................................PPPPPPPPPPPPP
..YYYYYYYYYYYYYY....................................................YYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY...............YYYYYYYYYYYYYY..............................PPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY....................................................YYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYY..............YYYYYYYYYYYYYYY.............................PPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY....................................................YYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYYYY..........YYYYYYYYYYYYYYYYY.............................PPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYY....................................................YYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYYYY..........YYYYYYYYYYYYYYYYY.............................PPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYYYY...........YYYYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY...............YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY...............YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY...............YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY......PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY...............YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY......PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
.
.
.
.
.
.
.
....................................PPPPPPP.....PP....PP....PPPPPP......PPPPPPP....PPP..PPP....PPPPPPP....PPPPPP........PPPP.......PPPPPP......PPPPPPP
....................................PPPPPPP.....PP...PPP....PPPPPPP.....PPPPPPP....PPP..PPP....PPPPPPP....PPPPPP........PPPP.......PPPPPP.....PPPPPPPP
....................................PPPPPPP.....PP...PPP....PPPPPPPP....PPPPPP.....PPP..PPP....PPPPPP.....PPPPPPP.....PPPPPPPP.....PPPPPPP.....PPPPPP
....................................PPP.........PP...PPP....PP....PP....PP.........PPP..PPP....PP.........PP...PPP....PP....PPP....PP...PP.......PP
....................................PPPPPP......PPPPPPPP....PP....PP....PPPPPP.....PPP..PPP....PPPPP......PP...PPP....PP....PPP....PP...PP.......PP
....................................PPPPPPP.....PPPPPPPP....PPPPPP......PPPPPP.....PPP...PP....PPPPP......PPPPPPPP....PP....PPP....PPPPPP........PP
.....................................PPPPPP.....PPPPPPPP....PPPPPP......PPPPP......PPP..PPP....PPPPP......PPPPPPP.....PP....PPP....PPPPP.........PP
.........................................PP.....PP...PPP....PPP.PPP.....PP..........PPPPPP.....PP.........PPP.........PP....PPP....PP.PPP........PP
.........................................PP.....PP...PPP....PP..PPP.....PPP.........PPPPPP.....PPP........PP..........PP....PPP....PP..PPP.......PP
....................................PPPPPPP.....PP...PPP....PP....PP....PPPPPPP......PPPP......PPPPPPP....PP............PPPP.......PP...PP.......PP
....................................PPPPPPP.....PP...PPP....PP....PP....PPPPPPP......PPPP......PPPPPPP....PP............PPPP.......PP...PP.......PP
`;

function CampusSprite() {
    return (
        <div className="sprite" style={{ '--sprite-aspect': `${COLUMNS} / ${ROWS}` }}>
            <PixelArt
                className="sprite__layer"
                art={LSUS}
                palette={PALETTE}
                columns={COLUMNS}
                rows={ROWS}
            />
        </div>
    );
}

export default CampusSprite;
