import PixelArt from '../PixelArt';

/**
 * The match.com wordmark: white lettering with the green dot, and
 * the two figures under a heart. 163x34, 4 colours.
 *
 * Traced at 168 columns, 3 cells per block of the source's own
 * ~37px pixel art. An arbitrary width would put each cell across two
 * source blocks and let the majority vote pick between them, which is the
 * speckle that makes a trace look glitchy.
 *
 * The lettering is white because the sign hangs in a night sky - an
 * earlier blue-on-navy version of this logo was barely legible there.
 *
 * Emitted by art/trace-logo.py - do not hand-edit.
 */
const COLUMNS = 163;
const ROWS = 34;

const PALETTE = {
    w: '#fdfdfd',
    b: '#0049c6',
    g: '#37df0b',
    p: '#fc025c'
};

const LOGO = `
....................................................................................................................................................ppp..pppp......
...................................................................................................................................................ppwppppwppp.....
...................................................................................................................................................pwppppppppp.....
...................................................................................................................................................ppppppppppp.....
...................................................................................................................................................ppppppppppp.....
....................................................................................................................................................ppppppppp......
......................................................................................................................................................ppppp........
.......................................................................................................................................................ppp.........
...................................................................................................................................................................
...................................................................................................................................................................
..................................................................................................................................................bbb..............
..................................................................wwww...........................................................................bbbbb.............
........................................wwww......................wwww...................................................................wwww....bbbbb....gg.......
........................................wwwww.....................wwww....................................................................ww.....bbbbb..ggggg......
........................................wwwww.....................wwww....................................................................ww.w....bbb...ggggg......
........................................wwwww.....................wwww............................................................................bbbb...gggg......
........................................wwwww.........w...........wwww....................................................................ww....bbbbbb....ggg......
www..wwwwww..wwwwww.......wwwwwwww....wwwwwwwwwww.....wwwwwwww....wwww..wwwww...............wwwwwww......wwwwwwww.....www.wwwww...wwwww.........bbbbbbbgg...gg.....
wwwwwwwwwwwwwwwwwwwww....wwwwwwwwwww..wwwwwwwwwww...wwwwwwwwwwww..wwwwwwwwwwwww...........wwwwwwwwww....wwwwwwwwww....wwwwwwwwwwwwwwwwww.......bbbbbbb.gggggggg....
wwwwwwwwwwwwwwwwwwwwww...wwwwwwwwwwww.wwwwwwwwwww..wwwwwwwwwwwww..wwwwwwwwwwwwww.........wwww....wwww..wwww....wwww...wwwwwwwwwwwwwwwwwww......bbbbbbb.gggggggg....
wwwwwwwwwwwwwwwwwwwwww...www....wwwww...wwwww.....wwwwww....wwww..wwwwww..wwwwww.........wwww.....ww..wwwww....wwwww..wwww...wwwww...wwww......bbbbbbbb....gggg....
wwwwww..wwwwww...wwwww...........wwww...wwwww.....wwwwww....www...wwwwww...wwwww.........www..........wwww......wwww..www.....www.....www......bbbbbbbbb...gggg....
wwwww....wwww.....wwww.....wwwwwwwwww...wwwww.....wwwww...........wwww......wwww.........ww...........www........www..www.....www.....www......bbbbbbbbb...ggggg...
wwwww....wwww.....wwww....wwwwwwwwwww...wwwww.....wwwww...........wwww......wwww.........ww...........www........www..www.....www.....www......bbbbbbbbb...gggggg..
wwwww....wwww.....wwww...wwwwwwwwwwww...wwwww.....wwwww...........wwww......wwww.........ww...........www........www..www.....www.....www........bbbbb....ggggggg..
wwww.....wwww.....wwww..wwwww....wwww...wwwww.....wwwww...........wwww......wwww.........ww...........www........www..www.....www.....www........bbbbb....gggggggg.
wwww.....wwww.....wwww..wwww....wwwww...wwwww.....wwwwww....www...wwww......wwww...ggg...www..........wwww......wwww..www.....www.....www........bbbbb..ggggggggggg
wwwww....wwww.....wwww..wwww...wwwwww...wwwww......wwwww....wwww..wwww......wwww..gggg...wwww.....ww...www......www...www.....www.....www........bbbbb...gggggggggg
wwwww....wwww.....wwww..wwwwwwwwwwwww...wwwwwwwww...wwwwwwwwwwww..wwww......wwww..ggggg...wwww...wwww..wwww....wwww...www.....www.....www........bbbbb.......gg....
wwwww....wwww.....wwww..wwwwwwwwwwwww....wwwwwwww...wwwwwwwwwwww..wwww......wwww..ggggg....wwwwwwwww....wwwwwwwwww....www.....www.....www........bbbbb.......gg....
wwwww....wwww.....wwww....wwwww..wwww.....wwwwwww.....wwwwwwww....wwww......wwww...ggg......wwwwwww.......wwwwwww.....www.....www.....www........bbbbb.......gg.g..
.................................................................................................................................................bbbbb.......gg.gg.
.................................................................................................................................................bbbbb.......gg..g.
.................................................................................................................................................bbbbb.......gg....
`;

function MatchLogoSprite() {
    return (
        <div className="sprite" style={{ '--sprite-aspect': `${COLUMNS} / ${ROWS}` }}>
            <PixelArt
                className="sprite__layer"
                art={LOGO}
                palette={PALETTE}
                columns={COLUMNS}
                rows={ROWS}
            />
        </div>
    );
}

export default MatchLogoSprite;
