import PixelArt from '../PixelArt';

/**
 * The Crimson Tide crest with "MHS" beside it: Minden High's signage, floating
 * in the sky over the photographed school. 178x59, 2 colours.
 *
 * Lifted wholesale from the old SchoolSprite, which drew this crest above a
 * 271-column trace of the building. The building is now the scene's
 * backdrop image, so only the signage is drawn - which took the scene from
 * about 7,400 rects to a few hundred.
 *
 * The lettering is drawn, not traced. Real letterforms at this size need their
 * stroke weight chosen deliberately, so M, H and S share one stem width.
 */
const COLUMNS = 178;
const ROWS = 59;

const PALETTE = {
    R: '#96272e',
    W: '#fdfefe'
};

const CREST = `
....................................................RRRRRRRRRRRRRRR...............................................................................................................
................................................RRRRRRRRRRRRRRRRRRRRRRR...........................................................................................................
................................................RRRRRRRRRRRRRRRRRRRRRRR...........................................................................................................
............................................RRRRRRRRRRRRRRRRRRRRRRRRRRRRR.........................................................................................................
.........................................RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR........................................................................................................
.........................................RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR........................................................................................................
........................................RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.......................................................................................................
.....................................RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.......................................................................................................
....................................RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWWWRRRRRR.....................................................................................................
...................................RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWWWWRRRRRR.....................................................................................................
.................................RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWWWWWWWRRRR.....................................................................................................
................................RRRRRRRRRRRWWWWWWWWWWWRRRRRRRRRRRWWWWRRRRRRRR.....................................................................................................
...............................RRRRRRRRRRRWWWWWWWWWWWWWRRRRRRRRRWWWWRRRRRRRRR.....................................................................................................
..............................RRRRRRRRRRWWWWWWWWWWWWWWWRRRRRRRRWWWWRRRRRRRRRR...........RRRRRRRRRRRRR....RRRRRRRRRRRRR.....RRRRRRRR..........RRRRRRRR.......RRRRRRRRRRRRRRRRRRRR..
.............................RRRRRRRRWWWWWWWWWWWWWWWWWWWRRRRRRWWWWRRR..RRRRR............RRRRRRRRRRRRR....RRRRRRRRRRRRR.....RRRRRRRR..........RRRRRRRR.......RRRRRRRRRRRRRRRRRRRR..
...........................RRRRRRRRRWWWWRRRWWWWWWWWWWWWWWWRRRWWWWWRR...RRRR.............RRRRRRRR.RRRRR..RRRRR.RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......RRRRRRRRRRRRRRRRRRRR..
...........................RRRRRRRRWWWWWRRRRWWWWWWWWWWWWWWRRWWWWWWRR....................RRRRRRRR.RRRRR..RRRRR.RRRRRRRR.....RRRRRRRR..........RRRRRRRR......RRRRRRRRRRRRRRRRRRRRRR.
..........................RRRRRRRWWWWWWWWRRRWWWWWWWWWWWWWWWWWWWWWWRR....................RRRRRRRR.RRRRR..RRRRR.RRRRRRRR.....RRRRRRRR..........RRRRRRRR......RRRRRRRRRRRRRRRRRRRRRR.
..........................RRRRRWWWWWWWWWWWRRRWWWWWWWWWWWWWWWWWWWWWRR....................RRRRRRRR..RRRRRRRRRR..RRRRRRRR.....RRRRRRRR..........RRRRRRRR.....RRRRRR............RRRRRR
.........................RRRRRRWWWWWWWWWWRRWRRRWWWWWWWWWWWWWWWWWWWRR....................RRRRRRRR..RRRRRRRRRR..RRRRRRRR.....RRRRRRRR..........RRRRRRRR.....RRRRRR..................
.......................RRRRRRWWWWWWWWWWWRWWWWRRWWWWWWWWWWWRRRRWWWRRR....................RRRRRRRR..RRRRRRRRRR..RRRRRRRR.....RRRRRRRR..........RRRRRRRR.....RRRRRR..................
.......................RRRRWWWWWWWWWWWWRRWWWWRRRWWWWWWWWRRRRWWWWWRRR....................RRRRRRRR...RRRRRRRR...RRRRRRRR.....RRRRRRRR..........RRRRRRRR.....RRRRRR..................
......................RRRRRWWWRRRRRWWWWRRWWWWWRRWWWWWRRRRWWRWWWWWRR.....................RRRRRRRR...RRRRRRRR...RRRRRRRR.....RRRRRRRR..........RRRRRRRR.....RRRRRR..................
......................RRRRWWRRRRRRRWWWWRRWWWRRRRWWWWRRWWWWWRWWWWRR......................RRRRRRRR...RRRRRRRR...RRRRRRRR.....RRRRRRRR..........RRRRRRRR.....RRRRRR..................
......................RRRRRRRRWWWWWWWWWRRRWRRWRRRWWRRWWRRRWRWWWWRR......................RRRRRRRR....RRRRRR....RRRRRRRR.....RRRRRRRR..........RRRRRRRR.....RRRRRR..................
......................RRRRRRRRWWWWWWWWWWRRRRRRRRRWWRWWWRRRRWWWRRR.......................RRRRRRRR....RRRRRR....RRRRRRRR.....RRRRRRRR..........RRRRRRRR.....RRRRRR..................
.....................RRRRRRRWWWWWWWWWWWWWRRRRRRRRWWRRWWRRRWWWWRRR.......................RRRRRRRR....RRRRRR....RRRRRRRR.....RRRRRRRRRRRRRRRRRRRRRRRRRR.....RRRRRR..................
...................RRRRWWWWWWWWWWWWWWWWWWWRRRRWWRWWRRRRRRRWWWWRR........................RRRRRRRR....RRRRRR....RRRRRRRR.....RRRRRRRRRRRRRRRRRRRRRRRRRR......RRRRRRRRRRRRRRRRRRRRRR.
..................RRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRRRRWWWWWRRR........................RRRRRRRR....RRRRRR....RRRRRRRR.....RRRRRRRRRRRRRRRRRRRRRRRRRR......RRRRRRRRRRRRRRRRRRRRRR.
..................RRRRWWWWWWWRRRRWWWWWWWRRRRRWWWWWWWWWWWWWWWWR..........................RRRRRRRR....RRRRRR....RRRRRRRR.....RRRRRRRRRRRRRRRRRRRRRRRRRR......RRRRRRRRRRRRRRRRRRRRRR.
.................RRRRWWWWRRRRRRRRWWWWWRRRWWRWWRRWWWWWWWWWWWRRR..........................RRRRRRRR...RRRRRRRR...RRRRRRRR.....RRRRRRRRRRRRRRRRRRRRRRRRRR......RRRRRRRRRRRRRRRRRRRRRR.
.................RRRWWWWWRRRRRWWWWWWWRRWRWWRWWRWRWWWWWWWWWWRRR......RRRRRR..............RRRRRRRR...RRRRRRRR...RRRRRRRR.....RRRRRRRRRRRRRRRRRRRRRRRRRR.......................RRRRRR
...............RRRRWWWWWRRRRRWWWWWWWWRRWRWWRWWRWWRWWWWWWWWWRRR.....RRRRRRRR.............RRRRRRRR...RRRRRRRR...RRRRRRRR.....RRRRRRRRRRRRRRRRRRRRRRRRRR.......................RRRRRR
...............RRRRWWWWRRRWWWWWWWWWWWRRRRWWRWWRWWRRWWWWWWWWRRR.....RRRRRRRRR............RRRRRRRR..RRRRRRRRR...RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......................RRRRRR
...............RRRWWWWRRRWWWWWWWWWWWWRRWRWWRWWRWWRRRWWWWWWWWRRRR.RRRRRRRRRRRR...........RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......................RRRRRR
...............RRRWWWRRRWWWWWWWWWWWWWWRRRRRRRRWWWWRRRWWWWWWWWWRRRRRRRRRRRRRRRR..........RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......................RRRRRR
...............RRRWWWRRRWWWWWWWWWWWWWWWRRRRRWWWRRWWRRWWWWWWWWWRRRRRRRRRRRRRRRR..........RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......................RRRRRR
...............RRRWWWRRRWWRRRRWWWWWWWWWWWWWWWRRRRRRWWRWWWWWWWWWWWRRRRRRRRRRRRR..........RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......................RRRRRR
...............RRRWWWRRRWRRRRRRWWWWWWWWWWWWWRRWWWRRRRWWWWWWWWWWWWRWWWRRRRRRRRR..........RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......................RRRRRR
................RRWWWRRRRR...RRWWWWWWWWWWWWWWWWWWWWRRWWWWWWWWWWWWWWWWRRRRRRRRR..........RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR.....RRRRRR............RRRRRR
.................RWWWWRRRR...RRWWWWWWWWWWWWWWWWWWWWWWWWRRRWWWWWWWWWWWRRRRRRRR...........RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR......RRRRRRRRRRRRRRRRRRRRRR.
.................RRWWWWWRR...RRWWWWWWWWWWWWWWWWWWWWWWWWWRRRRRWWWWWWWRRRRRRRRR...........RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR......RRRRRRRRRRRRRRRRRRRRRR.
.......RRRRRR....RRRRWWWWRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRRRRR............RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR......RRRRRRRRRRRRRRRRRRRRRR.
.......RRRRRR..RRRRRRWWWWRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR.............RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......RRRRRRRRRRRRRRRRRRRR..
....RRRRRRRRRRRRRWWRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRR..............RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......RRRRRRRRRRRRRRRRRRRR..
...RRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRRR.....................RRRRRRRR..............RRRRRRRR.....RRRRRRRR..........RRRRRRRR.......RRRRRRRRRRRRRRRRRRRR..
...RRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRRRRR............................................................................................................
..RRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRRRRRR...........................................................................................................
RRRWRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWRRRRRRWWWWWWWWWWWWWWWWWWWWWRRRRRRRRR..........................................................................................................
RRRWWRRRRRRRWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRWWWWWWWWWWWWWWWWWRRRRRRRRRR..........................................................................................................
RRWWWRRRRRRWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWWRRRRRRRRRRRR.........................................................................................................
RRWWWWRRRRWWWWWWWWWWWWWWRRRRRRRRRRR......RRRRRRWWWWWWWWWWWWWRRRRRRRRRRRRR.........................................................................................................
RRRWWWWWWWWWWWWWWWWWRRRRRRRRR..............RRRRRWWWWWWWWWWWWRRRRRRRRRRRRR.........................................................................................................
.RRRWWWWWWWWWWWWWWWRRRRR....................RRRRRWWWWWWWWWWWRRWWWRRRRRRRR.........................................................................................................
..RRRRWWWWWWWWWRRRRRRRRR.....................RRRRRRRWWWWWWWWWWWWRRRRRRRR..........................................................................................................
...RRRRRRRRRRRRRRRRR..........................RRRRRRRWWWWWWWWWWRRRRRRRR...........................................................................................................
....RRRRRRRRRRR.................................RRRRRRRWWWWWWWRRRRRRRR............................................................................................................
...................................................RRRRRRRRRRRRRRRRR..............................................................................................................
.......................................................RRRRRRRRRR.................................................................................................................
`;

function TideSprite() {
    return (
        <div className="sprite" style={{ '--sprite-aspect': `${COLUMNS} / ${ROWS}` }}>
            <PixelArt
                className="sprite__layer"
                art={CREST}
                palette={PALETTE}
                columns={COLUMNS}
                rows={ROWS}
            />
        </div>
    );
}

export default TideSprite;
